### ISSUE TITLE
LOW PRIO - imputena() - maxgap argument

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#1]
**POTENTIAL ISSUE**

**Issue: Unclear description of argument maxgap**

**Description of issue:** Is the point of maxgap to define the "max number of consecutive NAs that are allowed, i.e wont be imputed"? If so, I would consider rewriting the description in help slightly.
The current description "an integer denoting the maximum number of consecutive NAs to be filled", sounds like to me as if it would indicate the maximum number of NA's being filled. So for example, a maxgap of 6, should fill the 6 first element of 12 consecutive NAs. 

Currently, it will only fills these 12 NAs if maxgap = 13 or more.

**Screenshot:**
![image](https://github.com/zeugner/MDstats/assets/114997411/198203ac-f8fc-4a18-b31e-e1e35532d5ee)

**Comment by zeugner** [comment]
Thank you! fixed now :-)
