### ISSUE TITLE
MEDIUM PRIO - Bug in mds() when choosing too many countries

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#12]
**Issue:** When trying to choose too many different countries, there seems to be a max amount. 
When loading this data, if I do not specify geo it laods NUTS3 as well, which is a lot of loading for nothing. 

Note in the screenshot, that the successful line of code has one less country than the other. That seems to be the breaking point (16 successful, 17 not)

**Screenshot:**
![image](https://github.com/zeugner/MDstats/assets/114997411/a27d090e-ff94-4309-8cf4-74b3269ba062)

**Comment by zeugner** [comment]
this bug was due to autmatic line breaks occuring when input was treated a certain way. should be fixed with the new version.
