### ISSUE TITLE
MEDIUM PRIO - Cannot use a variable for filtering md3 object with ... notation

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#17]
**Issue:** In below screenshot, the first example shows a NA for 2023, while it should contain a value. If I instead use a , to separate the arguments, the expected result shows (with the exception of that 2023 is shown in the beginning. This is another issue, which I will create a separate ticket for).

**Screenshot:**
![image](https://github.com/zeugner/MDstats/assets/114997411/fa16bfc6-e045-4388-99a2-b51d520799ca)

**Comment by zeugner** [comment]
noted for the time series!
ii=c('AT','FR')
euhpq[1,1,,][ii,'2022'] #should work and is the same as euhpq[1,1,ii,'2022']

But
euhpq[1,1,,][ii.y2022]
is interpreted as a string and thus a call for country "ii", which is NA
(it is the same as euhpq[1,1,,]["ii.y2022"])


this is similar to dataframes. I added the follwing to the examples 
#'#Note that calling an element that does not exist will return NA,
#'#similar to data.frames with rownames
#' mm=euhpq[1,1,1:4,'2022']
#' testmat=as.data.frame(as.matrix(mm))
#' testmat['AT',] #has data
#' mm['AT',,drop=FALSE]
#' testmat['CH',] #has empty data
#' mm['CH',]
#' testmat[c('GG','FF'),]
#' mm[c('GG','FF'),]
