### ISSUE TITLE
MEDIUM PRIO - Copying an md3 object creates a "pointer" rather than a copy

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#19]
**Issue:** Pointer is probably not technically the right term, but in the below screenshot I try to make a copy of an MD3 object, but when I modify the copy, the original has also been modified. They therefore seem to "point" towards the same data.

**Screenshot:**
![image](https://github.com/zeugner/MDstats/assets/114997411/bbe8fbd8-e9c7-4045-9125-66dbdd3ce75e)
![image](https://github.com/zeugner/MDstats/assets/114997411/313eaba7-09ee-4ec3-9a55-1969a9ff1d22)

**Comment by zeugner** [comment]
this is a general feature of data.table . not sure whether we should fix this?

**Comment by tobhec** [comment]
I remember we discussed this before I left. 
Since it is a feature and not a bug, **this issue should be closed**. It would be useful to be able to copy as well though (but if I remember correctly there is a way to do that? Just dont remember how)

**Comment by zeugner** [comment]
you can simply use _copy_
e.g. testmd3=copy(euhpq)
