### ISSUE TITLE
LOW PRIO - Typos in error messages and outputs

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#2]
**LOW-PRIORITY BUG**

**Issue:**
Missing quotas in error messages where it suggest what code to try instead, which could lead **non-experienced** users to get confused.

1st screenshot helpmds("ESTAT/NAMA_10_GDP/.EUR..) is missing end-quota inside paranthesis.
2nd screenshot helpmds("ESTAT, pattern="YOUREXPRESSION") is missing end-quota after ESTAT

**Screenshots:**
`data <- mds("ESTAT/NAMA_10_GDP/.EUR..")`
![image](https://github.com/zeugner/MDstats/assets/114997411/9b811a06-9940-4b9a-8161-d7b4098075e4)

`helpmds("ESTAT", pattern = "trade")`
![image](https://github.com/zeugner/MDstats/assets/114997411/b4e4b6e5-1a65-4df5-bb5a-7acd181c17ba)

**Comment by zeugner** [comment]
Thank you! fixed now.
