### ISSUE TITLE
MEDIUM PRIO - Issue when trying to select too many variables when filtering

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#7]
**BUG**

**Issue:** When filtering an md3 object, there seems to be a limit on how many + you can have. At least in this specific case, it leads to an out of bounds error.

**Screenshot of error:**
![image](https://github.com/zeugner/MDstats/assets/114997411/fe5f556b-5de0-409d-b7f3-099fee3aa7f4)

**Screenshot without error (because I removed HPX_LINKED_NOMINAL):**
![image](https://github.com/zeugner/MDstats/assets/114997411/539bec77-87f8-4464-a5a5-07e5a7269d66)

**Note:**
I solved this temporarily by using : operator to get the range, but the problem I see with this approach is if  the order of the variable would for some reason change. Then we would get the wrong data, maybe without realizing it.
The second solution is to load two times, and combining. But this is just extra codelines.

**Comment by zeugner** [comment]
weird -will check!

**Comment by zeugner** [comment]
can you check the fix in the new vedrsion, pls?
manga tack!

**Comment by tobhec** [comment]
![image](https://github.com/zeugner/MDstats/assets/114997411/75a18707-e1c6-466e-93b8-04048c3d9122)

Error seem to persist.

**Comment by zeugner** [comment]
please try again: `?MD3` should now display version 0.1.3  ....?

**Comment by tobhec** [comment]
Problem solved!

Running source("https://s-ecfin-web.net1.cec.eu.int/directorates/db/u1/R/routines/installMDecfin.txt") did not properly update the package however.

Instead I ran install.packages('YOURPACKAGE',repos='https://s-ecfin-web.net1.cec.eu.int/directorates/db/u1/rpackages', INSTALL_opts = "--no-multiarch", type='source')) for all 4 packages, then it worked.
